### ISSUE TITLE
Couldn't find owner(s) IDs

### ISSUE THREAD

**Issue by dobrejpokus** [abdulrahman1s/Gabriel-bot#1]
Hello,
Today I dived into finding some effective AntiRaid Discord bot and I found this one. Everything looks great, but I just can't turn it on. I put a token in `.env`, I put my ID in `IGNORED_IDS` in `config.ts`, but it just writes me a message below whenever it starts. Can anyone help me?
Thanks.

![Couldn't find owner(s) IDs](https://user-images.githubusercontent.com/73689887/164973284-38da5279-bac9-4f12-9bf7-72609bbfb0fa.png)

**Comment by abdulrahman1s** [comment]
Did your bot have multiple owners?
It could be happen if your bot in team

**Comment by dobrejpokus** [comment]
Oh yeah, he's in team. I'll move him.

**Comment by dobrejpokus** [comment]
It's working fine now, thanks for helping!

**Comment by abdulrahman1s** [comment]
> It's working fine now, thanks for helping!

I'm happy you have been fix it, 
I recommend you to re check the project again since I've made a huge update includes some cool features. Just see the readme to get what I'm saying ☺️
